# Define 'Secret' to store db-credentials 
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials # Name of the 'Secret'
data:
  username: cm9vdA==  # base64 encoded 'Secret' username
  password: cm9vdA== # base64 encoded 'Secret' password